### ISSUE TITLE
FR: Estimate deployment costs

### ISSUE THREAD

**Issue by rainbreak** [dapphub/dapp#18]
Easy way to estimate gas costs in deploying a contract, ideally without actually deploying it.

**Comment by reverendus** [comment]
Should be easier to implement now as support in _seth_ is coming https://github.com/dapphub/seth/pull/5

**Comment by dbrock** [comment]
Maybe we don't even need this to be part of `dapp`? @rainbreak ?

**Comment by rainbreak** [comment]
It would just be sugaring, so you could do

```
dapp create --estimate MyContract
```

instead of writing exactly where `MyContract` is.

**Comment by dbrock** [comment]
yeah ok good point

**Comment by rainbreak** [comment]
There's another way of doing this that doesn't involve an rpc call:

```
echo $(($(wc -c < out/MyContract.bin) / 2 * (200 + 68) + 32000 + 32000))
```

`200` is the gas cost per byte for `CREATE`

`68` is the gas cost per byte for non-zero tx data

`32000` is the gas cost for a `CREATE` operation

`32000` is the gas cost for a contract creating transaction

I'm probably missing some subtleties, but this should give a pretty good estimation.

**Comment by dbrock** [comment]
Interesting...

Obviously I prefer doing an RPC call, lol --- but still...
