### ISSUE TITLE
tests fail with "Bad Instruction" error.

### ISSUE THREAD

**Issue by NiklasKunkel** [dapphub/dapp#19]
I ran into this while writing tests for ds-proxy. One of the tests for ds-proxy looks like this.

     function test_DSProxyExecuteProc() {

		//test contract bytecode
		bytes memory testCode = hex"60606040523415600b57fe5b5b609e8061001a6000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680630bcd3b3314603a575bfe5b3415604157fe5b60476065565b60405180826000191660001916815260200191505060405180910390f35b6000600160010290505b905600a165627a7a72305820cd1ba858674bd634c7ab2f54a43d025c7a9beedd22fc041d57777bb481c6a23e0029";

		//function identifier for getBytes()(bytes32)
		bytes memory calldata = hex"0bcd3b33";

		bytes32 response = proxy.execute(testCode, calldata);

		assertEq(response, bytes32(0x1));
	}

Running dapp test:

`[CRASH] test_DSProxyExecuteProc
    Dapple -> <DSProxyTest#d289>.test_DSProxyExecuteProc() => BadInstruction`

However then I create this test as a function in its own contract.

    pragma solidity ^0.4.8;
    import "./proxy.sol";
    contract foo {

	function trigger(address p) returns (bytes32) {

		DSProxy proxy = DSProxy(p);

		//test contract bytecode
		bytes memory testCode = hex"60606040523415600b57fe5b5b609e8061001a6000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680630bcd3b3314603a575bfe5b3415604157fe5b60476065565b60405180826000191660001916815260200191505060405180910390f35b6000600160010290505b905600a165627a7a72305820cd1ba858674bd634c7ab2f54a43d025c7a9beedd22fc041d57777bb481c6a23e0029";

		//function identifier for getBytes()(bytes32)
		bytes memory callData = hex"0bcd3b33";
		
		bytes32 response = proxy.execute(testCode, callData);
		return response;
	}
    }

Now when I call: `seth send <FooContractAddr> "trigger(address)(bytes32)" <ProxyContractAddr>`

It works and returns 0x1 correctly. You can also check the foo contract on etherscan to see that the transaction ran successfully.

**Comment by Findeton** [comment]
Hi I don't know if it's related but I have tested the following and it also gives me the "Bad Instruction" error:

Foo.sol file:
    pragma solidity ^0.4.13;

    contract Foo {
      function Foo() public {
      }

      function testf() public returns (bool) {
        return true;
      }
    }

Foo.t.sol file:
    pragma solidity ^0.4.13;

    import "ds-test/test.sol";

    import "./Foo.sol";

    contract FooTest is DSTest {
        Foo dos;

        function test_basic_sanity() {
            dos = new Foo();
            assert(true);
        }
    }

Shell output:

    findeton@findeton-H81M-S2H:/big/workspace/dapp-dos$ dapp test -v
    + dapp clean
    + rm -rf out
    + solc --overwrite ds-test/=lib/ds-test/src/ ds-test=lib/ds-test/src/index.sol --abi --bin --bin-runtime = -o out src/Foo.sol
    + solc --overwrite ds-test/=lib/ds-test/src/ ds-test=lib/ds-test/src/index.sol --combined-json=abi,bin,bin-runtime,srcmap,srcmap-runtime = src/Foo.sol
    + solc --overwrite ds-test/=lib/ds-test/src/ ds-test=lib/ds-test/src/index.sol --abi --bin --bin-runtime = -o out src/Foo.t.sol
    + solc --overwrite ds-test/=lib/ds-test/src/ ds-test=lib/ds-test/src/index.sol --combined-json=abi,bin,bin-runtime,srcmap,srcmap-runtime = src/Foo.t.sol
    Running 1 tests for src/Foo.t.sol:FooTest
    .
    + solc --link --libraries '' out/DSTest.bin out/Foo.bin out/FooTest.bin
    + dapp quicktest out
    Secp256k1 bindings are not compiled. Pure JS implementation will be used.
    Trying Foo, FooTest...
    F.

      [CRASH] testf
          -> new <cbd8d2>(...) => BadInstruction

    1 tests passed, 1 failed
    Took 0.193s

I don't know why it crashes. What's even stranger is that if I remove the testf function code, the test passes, even though testf was not called at any point.

**Comment by rainbreak** [comment]
@Findeton this issue is a bit of a catch all because `BadInstruction` is pretty generic.

In your case, the test is failing because `dapp` is a bit simplistic in looking for tests: it collects _all_ functions in your code that begin with `test...` and then executes them. However, the contract that contains this function does not inherit from `DSTest` and so fails as it doesn't have the other required things for running a test.
