### ISSUE TITLE
Syntax Error: Unexpected token - dapp-quicktest:74

### ISSUE THREAD

**Issue by dotnetspec** [dapphub/dapp#20]
dapp init 

on a new project:
then get:
![quicktest error](https://cloud.githubusercontent.com/assets/27340988/25513953/9d6356ba-2c0b-11e7-88a7-53a4bb8926b0.png)

**Comment by nanexcool** [comment]
@dotnetspec looks like your Nodejs is not recognizing the spread operator. Are you on Node 4? If so, you should upgrade to Node 6.

**Comment by dotnetspec** [comment]
Thanks. I thought being stuck at 4.2.6 might cause me trouble ...
[I've asked them for help on this](https://github.com/nodejs/help/issues/607)

**Comment by dotnetspec** [comment]
I was able to upgrade through Mint update manager. V6 nodejs simply appeared as an update and once applied it was recognized by the system.
