### ISSUE TITLE
make link causes Makefile:10: recipe for target 'link' failed error

### ISSUE THREAD

**Issue by dotnetspec** [dapphub/dapp#21]
OS: Linux Mint 18
Dapp Initialization
Make Link

Since I get 'file exists' should I just ignore this and move on to dapp init?:

''''
~/Downloads/dapp-master $ make link
mkdir -p /usr/local/{bin,libexec}
for x in bin/dapp libexec/dapp; do ln -s `pwd`/$x /usr/local/$x; done
ln: failed to create symbolic link '/usr/local/bin/dapp': File exists
ln: failed to create symbolic link '/usr/local/libexec/dapp/dapp': File exists
Makefile:10: recipe for target 'link' failed
make: *** [link] Error 1

''''
or should something be fixed first?

**Comment by nanexcool** [comment]
You should only call `make link` once. It's complaining that it already exists.

If you need, you can do a `make uninstall` then follow it with another `make link`

**Comment by dotnetspec** [comment]
Thanks. make link now without error
