### ISSUE TITLE
dapp init - make: *** [test] Error 127

### ISSUE THREAD

**Issue by dotnetspec** [dapphub/dapp#22]
Linux Mint 18
dapp initialization

I'm getting:
'''
xargs: shellcheck: No such file or directory
Makefile:13: recipe for target 'test' failed
make: *** [test] Error 127
'''
any ideas?
[console output.txt](https://github.com/dapphub/dapp/files/969350/console.output.txt)

**Comment by dbrock** [comment]
You shouldn't run `dapp` commands inside the `dapp` source directory, that will screw things up.

I suggest you remove your `dapp` source directory and start from the beginning as follows:

    git clone https://github.com/dapphub/dapp
    make link -C dapp
    mkdir my-dapp
    cd my-dapp
    dapp init

Let me know if  you run into any other problems.

**Comment by dotnetspec** [comment]
Noted. I'm inexperienced in Linux.
I'm now getting this:

philip-Inspiron-1525 Dapp Projects # rm -r dapp
philip-Inspiron-1525 Dapp Projects # git clone https://github.com/dapphub/dappCloning into 'dapp'...
remote: Counting objects: 1450, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 1450 (delta 19), reused 0 (delta 0), pack-reused 1400
Receiving objects: 100% (1450/1450), 3.01 MiB | 1.05 MiB/s, done.
Resolving deltas: 100% (321/321), done.
Checking connectivity... done.
philip-Inspiron-1525 Dapp Projects # make link -C dapp
make: Entering directory '/home/philip/Projects/Dapp Projects/dapp'
rm -r /usr/local/bin/dapp /usr/local/libexec/dapp
rm: cannot remove '/usr/local/bin/dapp': No such file or directory
rm: cannot remove '/usr/local/libexec/dapp': No such file or directory
Makefile:12: recipe for target 'uninstall' failed
make: *** [uninstall] Error 1
make: Leaving directory '/home/philip/Projects/Dapp Projects/dapp'


[console output.txt](https://github.com/dapphub/dapp/files/981691/console.output.txt)

**Comment by dbrock** [comment]
Sorry, `make uninstall` shouldn't fail. I just pushed a fix. Please try the same commands again.

**Comment by dotnetspec** [comment]
OK, now I get:

philip@philip-Inspiron-1525 ~/Projects/Dapp Projects $ su
Password: 
philip-Inspiron-1525 Dapp Projects # rm -r dapp
philip-Inspiron-1525 Dapp Projects # git clone https://github.com/dapphub/dapp
Cloning into 'dapp'...
remote: Counting objects: 1453, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 1453 (delta 21), reused 0 (delta 0), pack-reused 1400
Receiving objects: 100% (1453/1453), 3.01 MiB | 431.00 KiB/s, done.
Resolving deltas: 100% (323/323), done.
Checking connectivity... done.
philip-Inspiron-1525 Dapp Projects # make link -C dapp
make: Entering directory '/home/philip/Projects/Dapp Projects/dapp'
rm -rf /usr/local/bin/dapp /usr/local/libexec/dapp
mkdir -p /usr/local/{bin,libexec}
for x in bin/dapp libexec/dapp; do \
ln -s `pwd`/$x /usr/local/$x; done
ln: target '/usr/local/bin/dapp' is not a directory
ln: target '/usr/local/libexec/dapp' is not a directory
Makefile:10: recipe for target 'link' failed
make: *** [link] Error 1
make: Leaving directory '/home/philip/Projects/Dapp Projects/dapp'
philip-Inspiron-1525 Dapp Projects #

**Comment by dotnetspec** [comment]
OK, now I get:

philip@philip-Inspiron-1525 ~/Projects/Dapp Projects $ su
Password: 
philip-Inspiron-1525 Dapp Projects # rm -r dapp
philip-Inspiron-1525 Dapp Projects # git clone https://github.com/dapphub/dapp
Cloning into 'dapp'...
remote: Counting objects: 1453, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 1453 (delta 21), reused 0 (delta 0), pack-reused 1400
Receiving objects: 100% (1453/1453), 3.01 MiB | 431.00 KiB/s, done.
Resolving deltas: 100% (323/323), done.
Checking connectivity... done.
philip-Inspiron-1525 Dapp Projects # make link -C dapp
make: Entering directory '/home/philip/Projects/Dapp Projects/dapp'
rm -rf /usr/local/bin/dapp /usr/local/libexec/dapp
mkdir -p /usr/local/{bin,libexec}
for x in bin/dapp libexec/dapp; do \
ln -s `pwd`/$x /usr/local/$x; done
ln: target '/usr/local/bin/dapp' is not a directory
ln: target '/usr/local/libexec/dapp' is not a directory
Makefile:10: recipe for target 'link' failed
make: *** [link] Error 1
make: Leaving directory '/home/philip/Projects/Dapp Projects/dapp'
philip-Inspiron-1525 Dapp Projects #
