### ISSUE TITLE
'dapp' workflow for moving from Solidity to frontend (web3.js) development..

### ISSUE THREAD

**Issue by warren-bank** [dapphub/dapp#26]
@nmushegian
@dbrock
@apmilen

Hi all. Not sure if this would be of any interest to you..

Quick bit of context,
I've recently begun experimenting with the available tools for Dapp development.
Imho, when developing Solidity contracts.. the test harness in `dapp` is absolutely the best tool to use.

There seemed (to me) to be a bit of a gap in the `dapp` toolchain..
when one wants to move from developing Solidity contracts,
to using those compiled contracts to develop a frontend Dapp (ui).

I was playing around and experimenting over the past few days, and in doing so..
I kind of accidentally wrote 2 tools that compliment the `dapp` toolchain quite nicely,
and help to bridge that gap.

Today, I released the code for both projects to both github and npm.

github:
  * https://github.com/warren-bank/dapp-frontend
  * https://github.com/warren-bank/dapp-deploy

npm:
  * https://www.npmjs.com/package/@warren-bank/dapp-frontend
  * https://www.npmjs.com/package/@warren-bank/dapp-deploy

I have no idea if either of these tools would be of any interest or benefit to anyone else.
But, I just wanted to quickly make you all aware of their existence.
Hope you like!

- Warren :)

**Comment by warren-bank** [comment]
fyi..
I wrote a javascript REPL (console) last night to use in conjunction with the aforementioned tools.
It provides a very easy way to write (.js) scripts that can call functions in the deployed contracts.
I released the code earlier today:

github:
* https://github.com/warren-bank/dapp-console

npm:
* https://www.npmjs.com/package/@warren-bank/dapp-console

**Comment by nmushegian** [comment]
Just saw this, looks great. @dbrock ?

**Comment by warren-bank** [comment]
@nmushegian 
Thanks so much. I really appreciate the kind word.

@dbrock
(regarding the commit message in 062edd8)
Please don't apologize; If anything, I feel that I may be conflicting with you.
The naming convention was only intended as a way to loosely couple these tools into your workflow. But if you guys feel that they hijack your namespace.. please let me know, and I'll rename the symbolic links to something else.
