### ISSUE TITLE
How to test modifiers?

### ISSUE THREAD

**Issue by rstormsf** [dapphub/dapp#29]
lets say I have:
```
    modifier onlyOwner {
        if (msg.sender != owner) throw;
        _;
    }
```
How do I test it with ds-test framework?

**Comment by dbrock** [comment]
Well, you would simply test the functions that use the modifier. What's the problem with that?

**Comment by rstormsf** [comment]
I guess how do you change the owner to test that it fails.

**Comment by dbrock** [comment]
Ah, that's what you're asking. Okay, well, you can create a helper contract like so:

    contract Person {
        function callSomeFunction(YourThing thing, uint foo) {
            thing.someFunction(foo);
        }
    }

Then in your tests do like this:

    contract YourThingTest is DSTest {
        function testFail_unauthorized() {
            var thing = new YourThing();
            var alice = new Person();
            alice.callSomeFunction(thing, 123);
        }
    }

**Comment by rstormsf** [comment]
Got it. Thank you
