### ISSUE TITLE
Multiple dependencies causing remappings error

### ISSUE THREAD

**Issue by DeveloppSoft** [dapphub/dapp#40]
Hi, I found a small bug while installing multiple `ds-` dependencies.
Please find here the commands to deploy a testing repo:
```
cd <directory>
dapp init
dapp install ds-math
dapp install ds-token
dapp install ds-auth
```
And now, here is the bug:
```
dapp test
```
Which gives
```
+ dapp clean
+ rm -rf out
dapp-remappings: error: mismatching packages:
dapp-remappings: error: (1) lib/ds-auth/lib/ds-test/src
dapp-remappings: error: (2) lib/ds-math/lib/ds-test/src
```

**Comment by DeveloppSoft** [comment]
Could be caused by diffrerent `ds-test` package version

**Comment by DeveloppSoft** [comment]
Doing:
```
cd lib/ds-math
dapp upgrade ds-test
```
Fixed the previous erros, I will submit a pull to ds-math to upgrade `ds-test` version.
But, there is now the following error (root of of the repo):
```
dapp test
```
Gives:
```
+ dapp clean
+ rm -rf out
dapp-remappings: error: mismatching packages:
dapp-remappings: error: (1) lib/ds-math/src
dapp-remappings: error: (2) lib/ds-token/lib/ds-math/src
```

**Comment by DeveloppSoft** [comment]
First pull is dapphub/ds-math#6

**Comment by DeveloppSoft** [comment]
Upgrading `ds-math` should fix the last error too

**Comment by rainbreak** [comment]
Closing as this isn't a `dapp` issue. It's because our current ds-pkgs are out of sync with each other (which I've now fixed).
