### ISSUE TITLE
Event tests don't work

### ISSUE THREAD

**Issue by ryepdx** [dapphub/dapp#45]
Purposely writing failing event tests [per the documentation](https://dapp.readthedocs.io/en/latest/unit_testing.html#testing-events) and they're passing.

**Comment by nmushegian** [comment]
between this and the logging issue it looks like the entire test harness definition needs some attention, @mbrock what are your thoughts?

**Comment by alunperkins** [comment]
Also experiencing this issue - I cannot make the expectEventsExact fail no matter what events I tell it to expect or what events I fire.
