### ISSUE TITLE
Infinite loop if libexec/seth is not available

### ISSUE THREAD

**Issue by travs** [dapphub/dapp#51]
Recreate:
```
mkdir thing && cd thing
dapp init
make all
make deploy # just calls "dapp create Thing"
```

Output:
```
bash: warning: shell level (1000) too high, resetting to 1
```
(over and over)

Running:
```
linux 4.12.8-2-ARCH
zsh (inside tmux)
```

**Comment by travs** [comment]
I think I had an issue with one of the tools that dapp uses (`seth`, or maybe `ethrun` or `ethabi`). Anyway, reinstalled them using `make link` when possible, rather than just linking them to my `~/bin` dir in my path, and I don't get this error any more.

**Comment by dbrock** [comment]
Ahhh! That would make that happen. Thanks for the information.

Maybe this should be detected and a nice error message should be printed...
