### ISSUE TITLE
"dapp build" outputs bin/abi files in many subdirectories, not just one

### ISSUE THREAD

**Issue by travs** [dapphub/dapp#56]
[Source directory structure](https://gist.github.com/464361097bc95a00808baa5f95fbf29b)

`dapp build`

[Output directory structure](https://gist.github.com/anonymous/682d9bf63be411b79e9e83b3acdb5c39)

As you can see, there are many files that are repeated over and over in many subdirs of the output directory, but not so in the source directory.

My guess is that this happens when a contract in a subdir imports a file from another directory, but this could be wrong.

I suppose the relevant code is [here](https://github.com/dapphub/dapp/pull/52/files)?

One way to fix this is to just prune the extra files in `out/` afterwards, so that the trees look identical (dropping the `.bin`, `.sol`, etc. suffix, of course).

Let me know what you guys think!

**Comment by travs** [comment]
This is just `solc` doing its thing

**Comment by dbrock** [comment]
Hmm, weird
