### ISSUE TITLE
package doesn't exist

### ISSUE THREAD

**Issue by et** [dapphub/dapp#57]
In the [docs](https://github.com/dapphub/dapp/blame/e24b31b28396eba9c8d6da7715d6a8debfd50c27/docs/package_management.rst#L32), it says to install `dapp install apmilen/my-cool-package`. However, that repo does not exist.

**Comment by nmushegian** [comment]
It should say `dapp install ds-auth` based on the next example in that guide. (if you don't specify the org name it defaults to dapphub)

**Comment by nmushegian** [comment]
Ah I just read the context.. we'll rewrite for clarity
