### ISSUE TITLE
`dapp test` does not work on macOS due to `shopt -s globstar`

### ISSUE THREAD

**Issue by reverendus** [dapphub/dapp#63]
Due to `shopt -s globstar` in `dapp-test-ethrun`, the `dapp test` command fails on macOS. I presume `dapp debug` fill suffer the same issue as well.

**Comment by gbalabasquer** [comment]
Try this solution: https://apple.stackexchange.com/questions/291287/globstar-invalid-shell-option-name-on-macos-even-with-bash-4-x

**Comment by dbrock** [comment]
Fixed by 175da23117e84e2f492a268eddf4dfe0b4f7b359 737c4a5dd23c39c951abd46c9a4b4c10cf694c05
