### ISSUE TITLE
nix install error

### ISSUE THREAD

**Issue by nmushegian** [dapphub/dapp#68]
```
nikolai@thinkpod:~$ nix-env -iA dapphub.{dapp,seth,hevm,evmdis}
error: getting status of ‘/nix/store/i2h5pblgj748adny10bqhz3y060rnkrv-dapphub/dapphub/overlay/upstream/stable/dapp.nix’: No such file or directory
```

The directory exists all the way up to `stable`, the .nix just isn't there after following instructions on dapp.tools

**Comment by mbrock** [comment]
Oops, I recently turned on an automatic channel updater script that had a race condition; should be fixed now.
