### ISSUE TITLE
Watch mode for tests?

### ISSUE THREAD

**Issue by pospi** [dapphub/dapp#74]
Hi all,

Are there any plans to support file watching and incremental compilation / testing for contracts during development? Or is the general opinion that `hevm` is fast enough that an external tool should be used to trigger a rebuild & re-run?

**Comment by rainbreak** [comment]
We've not really discussed it. You could probably do incremental build (which uses `solc`) with something like `dapp build src/file.sol` (although for non large projects it's pretty quick to just build everything). Incremental test is more tricky, but you could perhaps construct a dependency tree and compare hashes of built contracts.

`hevm` is pretty quick though, so for small projects you might as well just run everything. For larger projects (e.g. makerdao/sai), it takes a bit longer as everything is in serial, but could maybe be parallelised (again).

Do you have a specific use case in mind? (size of project? in-editor usage?)

**Comment by pospi** [comment]
Nothing specific- but near-immediate feedback even for large projects is the goal I'm really hoping to fill. I guess you would need to keep a cache of the dependency tree from each test entrypoint file, and then re-run the affected tests if any files in the tree change?
