### ISSUE TITLE
`dapp test` libraries can break during setUp under specific conditions

### ISSUE THREAD

**Issue by wjmelements** [dapphub/dapp#78]
Previously: https://github.com/dapphub/ds-warp/issues/4

Libraries seem to have a dependency on contract file directory that manifests during `dapp test`.

Here is a minimum repro:

warptest.sol:
```
pragma solidity^0.4.18;
library Lib {
    struct Storage {
    }
    function getLen(Storage storage self)
    public view
    returns (uint256) {
        return 0;
    }
}
contract Doppel {
    using Lib for Lib.Storage;
    Lib.Storage lib;
    
    function getLen()
    public view
    returns (uint256) {
        return lib.getLen();
    }
}
contract Factory {
    function create()
    external {
        new Doppel();
    }
}
```
src/warptest.t.sol:
```
pragma solidity^0.4.18;

import "ds-test/test.sol";
import "ds-warp/warp.sol";

import "warptest.sol";

contract DSWarpTest is DSTest {
    Factory factory;
    DSWarp warp;

    function setUp() public {
        factory = new Factory();
        warp = new DSWarp();
    }
    function testInit() public {
        assertEq(warp.era(), now);
    }
}
```

The following solutions all fix the immediate test failure:
- moving the src file to the src dir
- not declaring library-dependent functions
- swapping the lines that initiate warp and factory in DSWarpTest.setUp

So something's broken, but it's complicated.

**Comment by rainbreak** [comment]
I'm reading that you don't have `warptest.sol` inside `src`, is that correct? Your source files need to be in the same directory, which is `src` by default.

**Comment by wjmelements** [comment]
That's correct. Symlinks seem to work, so that's good. I wasn't able to find a way to change the default directory from `src`.

I hope there's no related issue for dapp-installed libraries.

**Comment by rainbreak** [comment]
Your project layout should look something like this:

```
.
├── lib
│   └── ds-test
│       ├── Dappfile
│       ├── LICENSE
│       ├── Makefile
│       └── src
│           └── test.sol
├── Makefile
├── README
└── src
    ├── warptest.sol
    └── warptest.t.sol
```

The stuff in `lib` is added with `dapp install`. All your source files should be in `src`.

If you want to use a folder name other than `src` you can set the `DAPP_SRC` environment variable. Similarly `DAPP_LIB` changes the name of `lib`.
